### PR TITLE
Coverage

### PR DESCRIPTION
**Pull request by jdbancal**
Code coverage for replab

coveralls.io seems to be out of order, but I found a way to use codecov.io instead. You can see the result on https://codecov.io/gh/jdbancal/replab/branch/coverage , we have already a coverage of ~45%!

What will be needed for this to work on the main repo is to create an account linked to your github on codecov.io (it seems I cannot do that as I am not the owner of the organization, could only do it for my fork). Tests with code coverage are significantly slower, but go through.

### CODE REVIEW

**Comment by denisrosset** [comment]
Ooh beautiful! Should I just merge?

**Comment by jdbancal** [comment]
Yes, you can just merge it :)

To make the coverage effective, you'll probably need to activate the repo on codecov.io (at the moment it is using my repo, which doesn't have access to travis builds from https://github.com/replab/replab

**Comment by denisrosset** [comment]
BTW, you are admin on the replab repository, so I wonder why I have more privilege! Anyway, registering on codecov now.

**Comment by jdbancal** [comment]
Yes, I'm not sure also why I cannot access the replab organization on codecov...
Let me know once you have the address of the codecov page and I'll update the badges accordingly!

**Comment by denisrosset** [comment]
From the codecov doc:

```
Collaborators

Codecov uses GitHub permissions to authenticate users. No setup necessary.

Ask your team members to login to Codecov and they will have read/write access to the appropriate repositories.
```

**Comment by denisrosset** [comment]
BTW it is https://codecov.io/gh/replab/replab

**Comment by jdbancal** [comment]
Ok, I can see it in my codecov as well now... Thanks, I updated the badges!

**Comment by denisrosset** [comment]
Ok, weird thing: there is no coverage for the BSGS stuff; it's probably because the tests @bogdan98 added do not compute the group order. I'll add that.

**Comment by jdbancal** [comment]
It seems that these tests are not in the MOxUnit format. So they are probably not run by the test command.

**Pull request merged**
