### PR TITLE
Sphinx documentation generator

### PR DESCRIPTION
**Pull request by denisrosset**
Currently, there is only a single documentation page that recursively documents the whole library using docstrings.

@jdbancal : can you verify that you can make it work easily on your computer?

### CODE REVIEW

**Comment by jdbancal** [comment]
The pages produced look pretty cool!

Advantages that I see:
 - Documentation is extracted from the code (hence should be easily kept up to date)
 - Simple and automatic process
 - Nice output, the pages produced present nicely and are searchable

Potential pitfall that I see:
 - The same commented code is used for both display of help in the interactive matlab/octave console and API doc on the websits, but the comments are processed and thus interpreted differently in both cases. Therefore it won't be possible to have the best possible output at both ends. As an example, the insertion of latex code, while being rendered nicely on the website, produces a cryptic output in matlab/octave. See for instance the function `addCouplingConstraint` in https://opencobra.github.io/cobratoolbox/stable/modules/analysis/coupling/index.html: on matlab/octave, the output is

```
>> help addCouplingConstraint.m
  Constrains one (weighted) sum of fluxes to be above a lower bound.
  Appends to existing inequality constraints if they are present
 
  USAGE:
 
     modelConstrained = constrainRxnListAboveBound(model, rxnList, c, d, ineqSense)
 
  INPUTS:
     model:               model structure
     rxnList:             cell array of reaction names
 
  OPTIONAL INPUTS:
     c:                   `k x 1` vector :math:`c*v \geq d`
     d:                   `n x 1` vector :math:`c*v \geq d`
     ineqSense:           `k x 1` inequality sense {'L','G'}
 
  OUTPUT:
     modelConstrained:    constrained model:
 
                            * S - Stoichiometric matrix
                            * b - Right hand side = dx/dt
                            * C - Inequality constraint matrix
                            * d - Inequality constraint right hand side
                              :math:`[S; C] * v {=, \leq, \geq } [dxdt, d]`
```
writing `c*v >= d` as `:math:'c*v \geq d'` makes the documentation particularly painful to read. If we go this way, we should prioritize rendering for matlab/octave, avoiding unpleasant outputs as much as possible.

**Comment by denisrosset** [comment]
Agree. There is a Sphinx plugin that allows the use of $ syntax with LaTeX. I think some of the docstrings in Permutations.m use it.

**Comment by jdbancal** [comment]
The $ syntax is better, but in the context of the file Permutations.m, it seems to me that prioritizing rendering for matlab/octave would mean not using latex at all:
```
>> help replab.Permutations.quaternionGroup
  Returns a permutation representation of the quaternion group
 
  The quaternion group returned can be seen as the multiplication of 
  of the four quaternion generators 1, i, j, k with a sign +/-1, thus
  can be represented by permutations on 8 elements.
 
  Returns:
     +replab.PermutationGroup: Quaternion group as a subgroup of S(8)
```
is more readable than
```
>> help replab.Permutations.quaternionGroup
  Returns a permutation representation of the quaternion group
 
  The quaternion group returned can be seen as the multiplication of 
  of the four quaternion generators $1$, $i$, $j$, $k$ with a sign $\pm 1$, thus
  can be represented by permutations on 8 elements.
 
  Returns:
     +replab.PermutationGroup: Quaternion group as a subgroup of S(8)
```

**Comment by denisrosset** [comment]
Agree, the LaTeX notation does not add much, this was more for a test. (As you, I disliked the `:math:` syntax)

**Comment by jdbancal** [comment]
Of course I don't mean that we should never include latex or other interpreted text, but if possible avoid that it shows up in the console.

Apparently, if we break the comment section in two parts, like in the file addCouplingConstraint.m of the cobra toolbox, then the second part of the comment does not show up in matlab/octave, but still appears in Sphinx. Maybe this could be a good place to put interpreted text.

**Pull request merged**
