### PR TITLE
General decomposition method working on non-unitary representations directly

### PR DESCRIPTION
**Pull request by denisrosset**
Right now, the decomposition code finds first the change of basis matrix to make the representation to decompose unitary. This introduces additional computations and adds additional indirection layers to the algorithm. Also, the current algorithm embeds "magic epsilons" at several key steps.

This PR will not (yet) remove the magic epsilons, however the goal is to streamline the decomposition method, including making it work directly on non-unitary representations.

We will work with the following steps:

- [x] Introduce a "complex split" method which is comparable to the current "split" method, but which identifies complex conjugate pairs in representations. This step includes the addition of a flag in `SubRep` to mark real representations which encode such pairs.
- [x] Rework the code that identifies the type of real irreducible representations and canonicalizes their algebra.
- [x] Remove the old "cached samples" framework, and pass the required samples explicitly.

Non-goals are:
- The removal of magic epsilons and the use of proper error estimates instead.
- Include in the error bound the guarantees given by "divisionAlgebraName"
- The use of interval arithmetic.
- The iterative processing of `split` or `complexSplit` to provide irreducibility guarantees.

Such goals will be addressed in a second step.

### CODE REVIEW

**Comment by denisrosset** [comment]
Tests pass.

Needs additional tests, possible rework of CommutantVar @jdbancal , and then merge

**Comment by denisrosset** [comment]
@jdbancal If you refactor CommutantVar, please put an `assert` that the decomposition returned is unitary and has adjoint maps (`.hasAdjointMaps`). The decomposition algorithm is now fully general and does not necessarily requires unitary representations during the steps; thus, while the decomposition of a unitary representation is currently done providing adjoint maps, this is not guaranteed for the future.

This is of course a stop-gap measure, and later we'll incorporate support for non-unitary representations in SDP variables and constraints.

**Comment by jdbancal** [comment]
> @jdbancal If you refactor CommutantVar, please put an `assert` that the decomposition returned is unitary and has adjoint maps (`.hasAdjointMaps`). The decomposition algorithm is now fully general and does not necessarily requires unitary representations during the steps; thus, while the decomposition of a unitary representation is currently done providing adjoint maps, this is not guaranteed for the future.
> 
> This is of course a stop-gap measure, and later we'll incorporate support for non-unitary representations in SDP variables and constraints.

Thanks for mentioning the potential impact of this change! It's good to keep things in sync, will add these safety `asserts` in the updated version!

**Comment by jdbancal** [comment]
As discussed, really awesome improvements!

Two comments:
 - In 67995c475eca79f5379e23fda7a2fa691e6bf457 we did a comparison `if lambda > 0` but lambda could have a slight (numerical) imaginary component. This can potentially mess up the comparison: at some point in history, comparing two complex numbers in matlab ended up comparing their modulus (i.e. ignoring the sign). Octave followed the rule, but hasn't updated yet to the new rule of comparing only the real part yet, so better be careful here. I added `real` assuming that is what was meant, but didn't check if the same situation could arise elsewhere as well, maybe worth checking...
 - It seems to me that we have an undefined behavior when calling `W.isomorphismByFunction` in `WreathProductGroupTest.m` (surprises me that it didn't give an error). The reason is that the class `replab.prods.WreathProductGroup_finite` inherits from several classes which propose different implementations of the method `isomorphismByFunction` (see attached picture). It was detected here because Matlab chose the `replab.FiniteGroup` implementation and Octave chose of course the one from `replab.Group` ;-) provided in different branches (see also https://fr.mathworks.com/help/matlab/matlab_oop/subclassing-multiple-classes.html).
IMG_20210220_001548_491

**Comment by denisrosset** [comment]
Fixed the problem with `isomorphismByFunction` by splitting it in two methods:

- `isomorphismByFunctions`: plural, because both the preimage and image functions need to be provided
- `isomorphismByFunction`: singular, because for finite groups, the preimage function is provided by the BSGS mechanism

**Pull request merged**
