### PR TITLE
Better replab_init and help system

### LINKED ISSUE #257: RepLAB is incompatible with existing overloads of the help function
For example, it doesn't work well with the [matlab-emacs](https://sourceforge.net/projects/matlab-emacs/) package, which shows, in the help window
```
MATLAB Emacs help override recursion detected.  Exiting.
```

### LINKED ISSUE #258: Avoid path manipulations in handling the original help function

### PR DESCRIPTION
**Pull request by denisrosset**
This is a pretty big PR.

First, it cleans up the `replab_init` script; instead of trying all the initialization in that script, the script now adds the RepLAB source folder first, and then initializes the different dependencies by calling functions in the `replab.init` subpackage.

When adding RepLAB to the path, it now only adds the `replab/src` subfolder, and not the root folder (which only contains... `replab_init` and `replab_easyinstall`, scripts which are usually run either from the RepLAB directory itself, or with a fully qualified path).

Second, it overloads the built-in `help` function more carefully. The `help.m` is no longer present in the RepLAB path by default; rather, the path `src/help_overload` is added only when the situation is clean. The situation is clean when no other `help` overloads are present -- or only the `matlab-emacs` help overload is present.

Third, it changes the way we look up existing functions: in MATLAB, it uses the builtin `which(...,'-all')`, and in Octave it scans the path. This avoids using path manipulations.

Fourth, the `help` function itself was refactored into smaller pieces.

Fixes #257 
Fixes #258

### CODE REVIEW

**Comment by jdbancal** [comment]
Nice refactoring!

Ok, I did mostly minor adjustments as explained in each commit name. Some further comments below:

- When run from within the `replab/src` folder, `replab_init` could find the script `replab_Version` and hence failed to add the folder `replab/src`. This is problematic if the user later changes folder: he won't have access to replab commands anymore, and running `replab_init` again won't restore the functionality either, since the variable `allGood` in the script will be set to `true`. This is now fixed.

- If someone goes to the to replab folder to run `replab_init`, it should still be available afterwards (essentially all replab-related scripts should just start with a call to this function -- the call takes no time once a successful call has been made). Therefore, in my opinion the folder containing `replab_init` should be added to the path if it not there. I modified things accordingly.

- Detecting original Matlab/Octave help functions from path is nice, but I suppose we can't have any guarantee that these path structures will last for long (although hopefully this will be the case)... For more robustness and stability on the long term, and in a hope to minimize the effort needed to maintain these basic (and not very insightful) setup scripts, I added the recognition of original files based on content as well. This way, a `help` file that claims to be part of Octave will be assumed to be part of octave even if it lies in a new subfolder that we are not aware of as of today...

- I see some tests are failing, didn't check what is happening there

**Comment by denisrosset** [comment]
Thanks! Now it fails badly on Windows, I need to investigate.

**Comment by denisrosset** [comment]
@jdbancal Did a few corrections. Will change the `whichAll` function so that it doesn't consider the current directory as a valid path, except if it is present as an explicit path (Octave has a `.` path present by default).

**Comment by denisrosset** [comment]
Excluding the `callOriginalHelp.m` helper from coverage tests.

**Comment by denisrosset** [comment]
Finally!

**Pull request merged**
