### PR TITLE
Generating doctests using a Matlab/Octave script

### PR DESCRIPTION
**Pull request by denisrosset**
Idea: generate test functions using the MOxUnit library by crawling the source code and extracting the doctest blocks.

This branch has a file crawler, and reproduces the folder hierarchy under `tests/doctest` for now.

### CODE REVIEW

**Comment by denisrosset** [comment]
This is the way we'll move forwards with doctests. We can incorporate compatibility with Sphinx out of the box.

@jdbancal Referencing the closed #90 PR for the discussion about doctests

**Comment by denisrosset** [comment]
@jdbancal This PR is ready to be merged.

It extracts doctests and generate test files according to the following pattern:
```matlab
function test_suite = PermutationsTest()
  disp(['Setting up tests in ', mfilename()]);
  try
    test_functions = localfunctions();
  catch
  end
  initTestSuite;
end
function test1
  out = evalc('S5 = replab.Permutations(5); S5.order');
  assertEqualEvalcOutput(out, {'ans =' '120'});
end
```

**Comment by jdbancal** [comment]
Looks great!
I did some changes:
 - Corrected small bugs if there is more than one line of code in the test
 - Supported several lines of codes in different contexts:
    - if two lines of code are given in the same comment section, they give rise to a single test procedure
    - if two comment sections each contain a test, they are encoded in two distinct test procedures
 - Added a message telling where the error occured
 - Added a call to `replab_generatedoctests` in travis when runing the extensive test set

If ok with you we can merge :)

**Comment by jdbancal** [comment]
Note: it seems that this PR is going to merge into the branch `master`, instead of `develop`. Not sure if this can be corrected...

**Comment by jdbancal** [comment]
Note that we currently have two travis builds (see #81):
 1. One in which all tests are done, but without code coverage. The aim of this build is to check that everything is good, i.e. all tests pass.
 2. Another one with just the minimal tests, but with code coverage. The aim of this build is to generate a picture of the code coverage.

The reason we split the build process in two parts is because on travis, full tests with coverage take more than 50mn to complete, which means the job is killed (for reference, they take less than 2mn on a regular machine with matlab).

To my understanding, the main objective of doctests is to:
 - Make sure the `Example` section of the documentation always works (see #90), i.e. to test inline code sample (see #113)

To me, this is an important enough task (doctests appear in the user API!) that precludes charging them with additional responsibility. If doing so, the role of doctests would become ambivalent, and by experience, this is a free ticket for added troubles ;-)

To picture this, let us imagine that we would rely on doctests for code coverage. If this were the case, then doctests should test specific functions in every (or most) possible calling situations (like a good testing and coverage code should do). How would this be possible without including several `Examples` acting on various objects? It then becomes clear that such `Examples` would not be meant anymore to serve the user in his understanding of the code (remember that doctests appear in the API), but to serve the programmer in checking that all possible ways of calling a function work well. Such `Examples` would then be comparable to noise for the user, who would then naturally get the impression that he needs to understand all these example if he wants to understand how to use the function, although this is not the case.

On the other hand, if we say we don't rely on doctests for code coverage, then it seems logical not include them in the code coverage: otherwise they would give us the illusion that part of the code is covered although no coverage tests were written for them. Thus we would not realize that some tests are missing. If we want to test or cover some code, we need to write testing or covering code, not documentation.

This picture is maybe a bit extreme, because including doctests when running code coverage would still give use some meaningful idea of what code is covered. This is the reason why doctests are not disabled when `replab_runtests` is called with the option `withCoverage=true`. They are only disabled when setting the option `onlyFastTests=true`, which is the case in the second travis build.

**Pull request merged**
