### PR TITLE
Issue#239

### PR DESCRIPTION
**Pull request by jdbancal**
Here is a fix for #239 

The idea here is to estimate the accuracy of the crossing point, to make sure that we clearly overpassed it. This is done in two steps:

1. First we estimate the accuracy of the fit, to make sure the model gives a reasonably good description of the data (the crossing point is a property of the model). This is done with a [coefficient of determination](https://en.wikipedia.org/wiki/Coefficient_of_determination).
2. Estimate the uncertainty `Delta` on the crossing point by taking into account the finite number of samples. For a desired statistical evidence expressed in number `nSigma` of sigmas, the threshold after the crossing is chosen as `nSigma*Delta`.

### CODE REVIEW

**Comment by jdbancal** [comment]
Note that when trying to estimate the uncertainty on the crossing point using standard inference from the uncertainty of the fitted parameters, as in
```
% We estimate the uncertainty on the crossing
% point due to finite sampling
jacobian = [-1/slope; -(logfloor - offset)/slope^2; 1/slope];
variance = jacobian'*CovB*jacobian;
crossingDelta = sqrt(variance)*tinv(1-statParameter, iter - 3);
```
the obtained estimation appears to be clearly too small when `iter` is large (see picture below). I think the reason is that this approach implicitly assumes that the position of the crossing point is a function of the whole dataset, hence its uncertainty should decrease like `1/sqrt(iter)`. But in reality it is a function only of the last part of the data: as long as the data didn't start to saturate, we have no precise information about the position of the crossing point.

Hence, I found it more reliable to determine the uncertainty on the crossing point by finding the crossing point of a line decaying exponentially with equal slope as the fit, but shifted upwards by a constant proportional to the standard deviation of the fit residuals. This line is plotted in yellow below. To be compared with the crossing point in red, and the covariance-based estimation of the uncertainty on this point in blue.

image
From this picture, I wouldn't say that it is good enough to pass the blue line to be certain that we reached a plateau. I'm happier to stop after having reached the intersection of the yellow and red lines.

**Comment by denisrosset** [comment]
How was the coefficient of determination threshold (0.99) determined? Should we examine the behaviour of the fit on a few more examples before merging?

Also, would you like to write a short explanation of the convergence criterion for the documentation?

**Comment by jdbancal** [comment]
I think you're right, it's always good to check more examples! In fact, by playing a bit more, I found that our working hypothesis, which is that the shape of our curve is going to be two straight lines (one going down and the other one flat) is not correct ;-)

image

I think this shows that we should be more flexible. In particular, if the errors are small, say in [-eps, eps], then there is always a finite probability that the error at one round will be *very* close to zero. But in a log plot, this means a point *very* far from the model. I think we should not complain about points being too close to ideal...

In terms of the goodness of fit parameter, these points can incur a constant penalty. This means that the parameter doesn't converge to one (which indeed makes sense, since the data points diverge strongly and strongly (in the log plot) from the model).

image

So I think I'll adjust the model according to following stand: errors should be located below two straight lines, one with a negative slope, the other one with no slope.

Currently, the value of `0.99` was chosen by hand, a bit like the three sigmas. Sometimes people justify them as being generic values... but there is at least some degree of arbitrariness in them.

**Comment by denisrosset** [comment]
Should we skype about this?

**Comment by denisrosset** [comment]
Idea: should we make a "gallery" of examples for this issue?

**Comment by denisrosset** [comment]
Final comment: why not put the different stopping criteria under a feature flag (i.e. something in `replab.settings`, and merge)?

**Comment by jdbancal** [comment]
Sorry for not coming back to you earlier, I still wanted to try a few things... I was mostly posting pictures and comments here to track the progress and monitor the various behaviors observed.

Now I think I have something simpler, cleaner and which behaves better. In the end I gave up on the coefficient of determination, because I guess it could be problematic in some cases: in essence, it compares our fit with a fit by a horizontal line... but:

 - In principle a horizontal line is something we could observe (if there is no convergence at all)... so why should we take this as a reference case to compare with?
 - In practice, comparing between two alternative fits seems to be problematic: it some situations the data can suggest overwhelmingly that one fit is better than another one (e.g. a fit with two lines is clearly better than one with a single line), but yet, one of the lines can be an artefact, i.e. the preference quickly vanishes after a few more points are computed, and the single line hypothesis gets vindicated (see the first figure of #239 for such a case).

What seems to work well is to simply monitor the uncertainty we have on the various parameters of our model. We then wait until this uncertainty is small compared the the values we estimate (i.e. in relative terms). When all parameters have small uncertainties, and we are clearly beyond the crossover point, we conclude that we reached a meaningful saturation level.

**Comment by jdbancal** [comment]
From my perspective, this is ready to be merged now :) What do you think @denisrosset ?

**Comment by denisrosset** [comment]
@jdbancal I've merged too fast. The doc in `error_estimation.ipynb` was modified, but it's an auto-generated file, the source file is `error_estimation_source.ipynb`; thus the documentation still corresponds to the old convergence criteria.

**Comment by jdbancal** [comment]
Oh, sorry, I though I was modifying `error_estimation_source.ipynb`...

**Comment by denisrosset** [comment]
I'm going to try the use of `jupytext` for all notebooks in the Sphinx doc, that should solve that problem (and give us clean Git commits!)

**Pull request merged**
